sudo: required

services:
  - docker
env:
  matrix:
    - DOCKER_REPO_SLUG=anxolin/dotfiles-alpine DOCKER_FILE=Dockerfile-alpine
    - DOCKER_REPO_SLUG=anxolin/dotfiles-arch DOCKER_FILE=Dockerfile-arch
    - DOCKER_REPO_SLUG=anxolin/dotfiles-ubuntu DOCKER_FILE=Dockerfile-ubuntu
  global:
    - secure: "BmHMVquRBdNkQzX3UmKSQCHCMMke8xVpEkXRTCiLivvjb1pPu2ph+l3e+0Xj/kwOHqCH312zSjazzhxN7H4w1ddtydbVm1W67Arw40KfBANYmCYm9/w79Xhhigumb2i/laE0cHtpvb9zTJLhwiK4F3y2BxvlLR8sj9kham50Y2Gy7biaY7CDQjjk0Z7OVc/drQdw7TbNEoiZZpbDb/oG0Y/XxQXrV1PzOhUg/QDTtSQtR5cUhiZ9Gq1saWpxg+7x/4Eh2KPdrDTDQTnn7QjLSEg+59ByjzLR3Rnjqp/BWO6gfx7g3yHVe00QgsYTW5NP+7aPsBFMRxdXIoYMmIj4YSyFGhr/38INv6pWkqx9er6fmptT9poa148y2TCh2VztZUOlOdPQqFl+12qMxmUBaLcWppQPH82nmrxwLsN/GL9mSYNAL2Zt8Yqy7Xx8bkHqhrJy9QAcEmYXWPCV+XNawQMoQ2gyBfBS8boX2DBrK6o+1rk83Z40XB+ZcZR0jAvcjfTNmNu1w5rwE4CvvbGnQS7pqVWbl3TnAXmCulMqRivJEm+qMNjoFsdpm++CWco+E3CKoVZFSK55Fh8F4Qk9SWQ38ienDRWc6h3dmN1Rx04baZs/jeKOT19qemJqMhEPlQdixbofCDOmvV2bEMy7ckbVO1zfjr6L+iLuKtfEJUw="
    - secure: "UxoQ5Q+mHHBz6MycSmvDN9+off7CF98tFnGppeDecHgSS2WbckwXtSmQPl2jCUqLA4aGfu3p6+SD9O1z30HLgux+blEVYMdGfhhHQVDzZRfd77eH0JANcOlHBN+DfKK0t/szMDfshX130cv5csx8FnMuEB7Lg6aJwSqnpYbjCWCMfvWTS+qy8XUu3hzG2qRnCmxrf5hpcfjreuY2eAL1HI+N5RnRiTGRkCzp7upwvlGG/5u21v3rDk7x72X2JcwJy4uMqFplDJyyraSL0hJx9e+ifxSieWMcBUErwCz0OuaMcdaJIZH+G59mYEO9lClPYWBKt9vo2/PR2OKdwWL65Lxri9U1+jsLPpVP1y/K1gnpik7exrbCJh82PDm+OsuDjLPyT85rU9cueR4ikEofUlxe+6G8y9T1QwsRw5KdntMui6eTcEBxmXMWEapU4JbIo8aZDeGkzGtniRRrNTCaExBrtEBRCavuG+P+iV0PrEIcRV5BjiLNDIGUhGJCeBTO77bMquqhKmqEHonxWNGGt3/dqVuMrBfFvEngGY3QdoIpDgTXzYgtQ3CAGq/0BvKeJJq17tOQKywNYNpM98tsC6ajZGYdxhME2EVSJ1mc6o9+vYCKgfvJHGUBcnb+8hdOD6gvfvatYpswn1NH/o8HKBaTAZbZLzPFRtPbAqUFruo="

script:
  # Build latest
  - docker build -f $DOCKER_FILE -t $DOCKER_REPO_SLUG:latest .
  # Build tag
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then docker build -f $DOCKER_FILE -t $DOCKER_REPO_SLUG:$TRAVIS_BRANCH .; else true ; fi
after_success:
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push to latest if master branch
  - if [[ $TRAVIS_BRANCH = master ]]; then docker push $DOCKER_REPO_SLUG:latest; else true; fi
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then docker push $DOCKER_REPO_SLUG:$TRAVIS_TAG; else true ; fi
