# docker -it 820613b91511 sh
FROM archlinux/base:latest

MAINTAINER Anxo Rodriguez "anxolin@gmail.com"

ENV DOTFILES_USER=anxo
ENV DOTFILES_REPO=https://github.com/anxolin/dotfiles.git

# TODO: Review if I can remove the apps here and let them be install with install.sh
# vim, vim-nox, or vim+gvim??
RUN echo "**********  Update dependencies  **********" \
  && pacman -Syu --noconfirm \
  #
  && echo "**********  Install base packages **********" \
  && pacman -S --noconfirm base-devel \
  #
  && echo "**********  Install vim, tmux, zsh, git  **********" \
  && pacman -S --noconfirm vim tmux zsh git \
  #
  && echo "**********  Install some dependencies for tmux and vim  **********" \
  && pacman -S --noconfirm \
    the_silver_searcher \
    xclip \
    ctags \
    cmake \    
    openssh \
    bc \
  #
  && echo "**********  Install Node, npm, yarn  **********" \
  && pacman -S --noconfirm nodejs npm yarn \
  && echo "**********  Install Python3  **********" \
  && pacman -S --noconfirm python \
  && echo "**********  Setup user $DOTFILES_USER  **********" \
  && useradd -m -s /bin/zsh $DOTFILES_USER \
  #
  && echo "**********  Add $DOTFILES_USER to sudoers  **********" \
  && usermod -aG wheel $DOTFILES_USER \
  && echo '%wheel ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \  
  #
  && echo "**********  Cleanup packages  **********" \
  && pacman -Rns $(pacman -Qtdq) || true \
  && rm -rf /var/cache/pacman/pkg

USER $DOTFILES_USER

RUN echo "**********  Install Dotfiles  **********" \
  && git clone $DOTFILES_REPO /home/$DOTFILES_USER/dotfiles \
  && chmod +x /home/$DOTFILES_USER/dotfiles/install.sh \
  && /home/$DOTFILES_USER/dotfiles/install.sh \
    --skip-install-apps \
    --skip-install-vim-plugins  

WORKDIR /home/$DOTFILES_USER/dotfiles

CMD tmux
