# docker run -u anxo -it 820613b91511 sh
FROM alpine:latest

MAINTAINER Angel Rodriguez "anxolin@gmail.com"

ENV DOTFILES_USER=anxo
ENV DOTFILES_REPO=https://github.com/anxolin/dotfiles.git

# Install some basic apps
#   - Since we are compiling vim with python3 support, we need some dependencies first
#   - Install other basic apps like git, zsh, tmux
#   - Then install some apps that vim plugins depend on: xclip, ctags, ag, ...
RUN \
  apk add --no-cache \
    gcc make ncurses-dev ncurses python-dev python3-dev python python3 ctags nodejs-npm musl-dev su-exec \
    git \
    zsh \
    tmux \
    vim \
    the_silver_searcher \
    xclip \
    ctags \
    cmake \
    openssh \
  && cd /tmp && git clone https://github.com/vim/vim.git && cd vim \
  && ./configure --enable-pythoninterp --prefix=/usr --with-python-config-dir=/usr/lib/python2.7/config --enable-python3interp \
  && make && make install \
  && addgroup $DOTFILES_USER \
  && adduser -Ds /bin/zsh $DOTFILES_USER -G $DOTFILES_USER

USER $DOTFILES_USER

RUN \
  git clone $DOTFILES_REPO /home/$DOTFILES_USER/dotfiles && \
  chmod +x /home/$DOTFILES_USER/dotfiles/install.sh && \
  sh -x /home/$DOTFILES_USER/dotfiles/install.sh

WORKDIR /home/$DOTFILES_USER/dotfiles

CMD zsh
