# docker run -u anxo -it 820613b91511 sh
FROM ubuntu:latest

MAINTAINER Anxo Rodriguez "anxolin@gmail.com"

ENV DOTFILES_USER=anxo
ENV DOTFILES_REPO=https://github.com/anxolin/dotfiles.git
ENV DEBIAN_FRONTEND=noninteractive

# Set the locale
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8   

RUN \
  apt-get update \
  && apt-get install -y \
    locales \
    sudo \
    zsh \
    tmux \
    git \
    vim-nox \
    silversearcher-ag \
    xclip \
    ctags \
    cmake \
    openssh-client \
    bc \
  && adduser --disabled-password --gecos "" $DOTFILES_USER \
  && adduser $DOTFILES_USER sudo \
  && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
  && rm -rf /var/lib/apt/lists/* \
  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen


USER $DOTFILES_USER

RUN \
  git clone $DOTFILES_REPO /home/$DOTFILES_USER/dotfiles \
  && chmod +x /home/$DOTFILES_USER/dotfiles/install.sh \
  && /home/$DOTFILES_USER/dotfiles/install.sh \
    --skip-install-apps \
    --skip-install-vim-plugins \
  && sudo rm -rf /var/lib/apt/lists/*

WORKDIR /home/$DOTFILES_USER/dotfiles

CMD tmux
