# docker -it 820613b91511 sh
FROM archlinux/base:latest

MAINTAINER Anxo Rodriguez "anxolin@gmail.com"

ENV DOTFILES_USER=anxo
ENV DOTFILES_REPO=https://github.com/anxolin/dotfiles.git

# TODO: Review if I can remove the apps here and let them be install with install.sh
# vim, vim-nox, or vim+gvim??
RUN \
  useradd -m -s /bin/zsh $DOTFILES_USER \
  && usermod -aG wheel $DOTFILES_USER \
  && echo '%wheel ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
  && pacman -Syu --noconfirm \
  && pacman -S --noconfirm \
    gvim \
    git \
    zsh \
    tmux \
    vim \
    the_silver_searcher \
    xclip \
    ctags \
    cmake \
    base-devel \
    openssh \
  && pacman -Rns $(pacman -Qtdq) || true \
  && rm -rf /var/cache/pacman/pkg

USER $DOTFILES_USER

RUN \
  git clone $DOTFILES_REPO /home/$DOTFILES_USER/dotfiles \
  && chmod +x /home/$DOTFILES_USER/dotfiles/install.sh \
  && /home/$DOTFILES_USER/dotfiles/install.sh \
    --skip-install-apps \
    --skip-install-vim-plugins \
  && pacman -Rns $(pacman -Qtdq) || true \
  && rm -rf /var/cache/pacman/pkg

WORKDIR /home/$DOTFILES_USER/dotfiles

CMD zsh
