"  **********   BASIC CONFIG      **********

" Use Vim, vi is not compatible
set nocompatible              " be iMproved, required
filetype off                  " required

" UTF8 Encoding
set encoding=UTF-8
  
" History
set history=80

" Enable line numbers (hybrid: absolute + relative)
set number
set relativenumber

" Do not wrap lines and when scroll horilzontally, show 25 chars of context
set nowrap
set sidescroll=25

" Set Meslo font patched for PowerLevelPk10
"   See https://github.com/anxolin/dotfiles/blob/master/README.md#L113
if has('gui_running')
  set guifont=MesloLGS-NF-Regular:h12
endif

" If we are in the:
"   - last char and press `l` (or right arrow) we jump to next line's first char
"   - first char and press `h` (or left arrow) we jump to the previous last
"     char
"   - IMPORTANT: Some people recommend against using the 'h' and 'l' also.
"     this for breaking some plugin no sure why, so I'll leave it as a test :)
set whichwrap=b,s,<,>,[,],h,l

" Enable syntax highlight and plugin support
syntax on

" Truecolor (24-bit) — required for catppuccin to look right.
" Inside tmux/screen, vim needs the t_8f/t_8b escape sequences set explicitly.
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

" filetype: Enable plugin
"   * Detects the filetype (using the extension or the hashbang)
"   * Allows to hightlights depending on the filetype
"   * Uses filetypes plugins depending on the language (cames with defaults
"     for common languages)
"   * Apply language specific idengt rules see :filetype-indent-on
filetype plugin on


" TempFiles: Change backup dir for .swp files
set backupdir=~/.vim/backup_files/
set directory=~/.vim/swap_files/
set undodir=~/.vim/undo_files/

" Set 2 spaces for tabs
set ts=2

" Spaces instead of tabs
set expandtab
set shiftwidth=2
set softtabstop=2

if has("gui_running")
  set linespace=6
endif


" copy/paste integration
"   * in order to work vim must have been compiled with the clipboard flag
"       :echo has('clipboard')
"   * important, for working with tmux it's important to have
"       reattach-to-user-namespace
set clipboard=unnamed

" Make backspace work like most other apps (allows to remove the <br> chars of
" the previous line)
set backspace=indent,eol,start

" Activate mouse
set mouse=a

" Options ported from nvim init.lua
set timeoutlen=300       " short wait for chord completion (was 1000ms — caused <leader>l to hang for lazygit)
set ttimeoutlen=10       " key code sequence wait
set smartcase            " case-insensitive unless query has uppercase
set smartindent          " auto-indent on new lines
set scrolloff=5          " keep 5 lines visible above/below cursor
set sidescrolloff=5      " keep 5 columns visible on either side
set splitright           " :vsplit opens to the right
set splitbelow           " :split opens below
set cursorline           " highlight current line
set lazyredraw           " don't redraw during macros (faster)
set signcolumn=yes       " always show sign column (no jitter from coc/gitgutter)

" Automatically jump to end of text you pasted:
"   This way you can paste many times with pppppp...
vnoremap <silent> y y`]
vnoremap <silent> p p`]
nnoremap <silent> p p`]

" Use c-a and c-e for the "go-to begin/end" of the line in editing mode
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>^

" Insert-mode word movement (Alt+Left/Right and Alt+b/f/h/l)
inoremap <M-Left>  <C-o>b
inoremap <M-Right> <C-o>w
inoremap <M-b> <C-o>b
inoremap <M-f> <C-o>w
inoremap <M-h> <C-o>b
inoremap <M-l> <C-o>w

" Insert-mode delete word backward/forward
inoremap <M-BS> <C-w>
inoremap <M-d>  <C-o>dw
inoremap <C-d>  <Del>

" Normal-mode word movement and forward delete
nnoremap <M-Left>  b
nnoremap <M-Right> w
nnoremap <Del> x

" Clear search highlight on Esc (mirrors nvim init.lua:109)
nnoremap <silent> <Esc> :nohlsearch<CR>


" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>

" Autoread: Detect changes done by external applications
"   - autoread: reads the file when changed from the outside (but it doesnt work
"     on its own, there is no internal timer or something like that)
"   - CursorHold * checktime: when the cursor isn't moved by the user for the
"     time specified in 'updatetime' (which is 4000 miliseconds by default)
"     checktime is executed.
"     Checktime forces the autoread to execute.
"   - call feedkeys("lh"): Moves the cursor left and right, so CursorHold is
"     triggered again later (basically, we create a loop)
"   - FIXME: I had to remove 'call feedkeys("lh")' because with unsaved buffers
"			was making a BEEP every checktime!
"set autoread | au CursorHold * checktime | call feedkeys("lh")
set autoread | au CursorHold * checktime

" Restore cursor position when reopening a file (mirrors nvim init.lua:161)
augroup LastPosition
  autocmd!
  autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | execute "normal! g`\"" | endif
augroup END


" Spell: Enable spell suggestions
" set spelllang=en,es
set spell

" Enable wild menu: Display all matching options when we press tab (e.g. :find *.js)
set wildmenu


" **********     Functions     **********
function! Message(msg, ...) abort
    let l:duration = get(a:, 1, 800)
    echo a:msg
    call timer_start(l:duration, { _ -> execute('echo ""') })
endfunction

function! HasPlugins(name)
    return isdirectory($HOME . '/.vim/plugged/' . a:name)
endfunction


" **********     Custom Commands     **********
" BufOnly: Close all buffers except the current one
command! BufOnly %bd|e#


" **********     LEADER and custom MAPPINGS     **********
" Set SPACE as the leader key
" let mapleader = "\<Space>"
let mapleader=" "


" Leader mappings:
" https://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
"   open a new file
nnoremap <Leader>o :CtrlP<CR>
"   save file
nnoremap <Leader>w :write<CR>
"   quit
nnoremap <Leader>q :quit<CR>
"   quit all (force)
nnoremap <Leader>Q :qa!<CR>
"   Copy & paste to system clipboard with <Space>p and <Space>y:
vmap <Leader>y "+y
vmap <Leader>d "+d
" Move among buffers with SPACE arrows
map <Leader><Right> :bnext<cr>
map <Leader><Left> :bprev<cr>

" Window navigation with Ctrl+hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Tab navigation with <Leader><Arrows>
nnoremap <Leader><Left>  :tabprevious<CR>
nnoremap <Leader><Right> :tabnext<CR>
" Tab navigation with Leader+h/l as fallback
nnoremap <Leader>h :tabprevious<CR>
nnoremap <Leader>l :tabnext<CR>
" Tab navigation with Alt+Tab (may not work in all terminals/OS)
nnoremap <A-Tab> :tabnext<CR>
nnoremap <M-C-Y> :tabprevious<CR>
" Tab navigation with Alt+[ / Alt+]
nnoremap <A-]> :tabnext<CR>
nnoremap <A-[> :tabprevious<CR>
" Close current tab
nnoremap <C-w>q :tabclose<CR>
" Jump to tab N with Alt+1..9
for s:i in range(1, 9)
  execute 'nnoremap <A-' . s:i . '> ' . s:i . 'gt'
endfor

" Reload vimconfig with SPACE+r
map <Leader>r :source ~/.vimrc<cr>:call Message("⚡️ reloaded!")<cr>

" Python: insert ipdb breakpoint
au FileType python map <Leader>b Oimport ipdb; ipdb.set_trace() # BREAKPOINT<C-c>

" Use vim expand region with v key: /terryma/vim-expand-region
"   Use v for selecting a letter, vv to select a word, and so on...
"   Use c-v to decrese selection
"     The default was: + and _
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" Ignore case by default when searching
set ignorecase

" Search: Hightlight increasilly while typing
set incsearch

" Highlight a word on double click (also using *)
map <2-LeftMouse> :set hlsearch<CR>*
imap <2-LeftMouse> :set hlsearch<CR><c-o>*
set hlsearch
nnoremap <F3> :set hlsearch!<CR>

" vim-plug: Plugin manager
"   Brief help
"     :PlugList       - lists configured plugins
"     :PlugInstall    - installs plugins; append `!` to update or just :PlugUpdate
"     :PlugSearch foo - searches for foo; append `!` to refresh local cache
"     :PlugClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
"   see :h vim-plug for more details or wiki for FAQ
"   Put your non-Plug stuff after this line
"
" vim-plug installation: set the runtime path to include vim-plug and initialize

" If vim-plug plugin is present
if filereadable(expand('~/.vim/autoload/plug.vim'))
  " Use the same plugin directory for both Vim and Neovim
  call plug#begin('~/.vim/plugged')

  " *******  Plugins *************

  " Plugin that jumps to the matching HTML tag or if/else/elseif using %
  packadd! matchit

  " vim-plug: let vim-plug manage vim-plug, required
  Plug 'junegunn/vim-plug'

  " Catppuccin: Theme - https://github.com/catppuccin/vim
  Plug 'catppuccin/vim', { 'as': 'catppuccin' }

  " vim-polyglot: A collection of language packs for Vim.
  Plug 'sheerun/vim-polyglot'

  " Ack: Run your favorite search tool from Vim, with an enhanced results
  " list. (ag silversearch, 
  Plug 'mileszs/ack.vim'

  " Plugins that depend on NodeJS
  "   - If nodejs available CoC is used for code completions, linter, etc
  "   - Otherwise, there's a fallback with other plugins
  if executable('node')
    " CoC: Conquer of Completion
    "   - Code completions, similar to YouCompleteMe, but easier to setup!
    "   - Config file: 
    "       ~/.config/coc
    "       ~/dotfiles/vim/coc-settings.json
    "   - Work with extension (i.e ts-server)
    "      https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions
    "      https://github.com/neoclide/coc-tsserver
    Plug 'neoclide/coc.nvim', { 'branch': 'release' }
    " Extensions are installed via g:coc_global_extensions below.

  else
    " ALE: Asynchronous Lint Engine — fallback when nodejs (and CoC) is unavailable
    Plug 'w0rp/ale'
  endif


  " Javascript:  syntax highlighting and improved indentation.
  Plug 'pangloss/vim-javascript'

  " TypeScript
  Plug 'leafgarland/typescript-vim' 

  " JS and JSX
  Plug 'maxmellon/vim-jsx-pretty'   

  " GraphQL
  Plug 'jparise/vim-graphql'       

  " Fugitive: Git - Vim Fugitive:
  "   Vim plugin
  Plug 'tpope/vim-fugitive'
  " Rhubarb: GitHub integration for Fugitive (:GBrowse to open file in browser)
  Plug 'tpope/vim-rhubarb'

  Plug 'tpope/vim-commentary'    " gcc / gc{motion} to toggle comments
  Plug 'tpope/vim-surround'      " cs/ds/ys for surrounding chars
  Plug 'tpope/vim-repeat'        " makes . repeat plugin maps too
  Plug 'airblade/vim-gitgutter'  " +/-/~ markers in sign column for unstaged hunks

  " Airline: Status bar - Vim Airline
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  " (catppuccin airline themes ship inside the catppuccin/vim plugin above)

  " FLZ for vim
  "   fzf#install() makes sure that you have the latest binary, but it's 
  "   optional, so you can omit it if you use a plugin manager that doesn't support hooks.
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'

  " Ctrlp: Ctrl+p - ctrlp.vim - Open files by name
  Plug 'ctrlpvim/ctrlp.vim'

  " Ctrlp: Extension to allow to delete open buffers (ctrlp_bdelete)
  Plug 'j5shi/ctrlp_bdelete.vim'

  " NerdTree: File explorer
  Plug 'scrooloose/nerdtree'  

  " vim-nerdtree-syntax-highlight
  "   Meant to be use with vim-devicons. Adds better icons and colours
  Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

  " Async run: skywind3000/asyncrun.vim
  Plug 'skywind3000/asyncrun.vim'

  " Vim expand region: Allows to selects blocks of code and increase the
  " selection to next block easily
  Plug 'terryma/vim-expand-region'

  " EasyMotion: disable default mappings (we want <leader><leader> for :Files,
  " and we set the easymotion bindings we use explicitly below)
  let g:EasyMotion_do_mapping = 0
  Plug 'easymotion/vim-easymotion'

  " Vim-devicons: 
  "   IMPORTANT: Needs to go last
  "   Add nice icons to NERDTree, vim-airline, CtrlP, powerline, 
  "   denite, unite, lightline.vim, vim-startify, vimfiler, vim-buffet and flagship.
  Plug 'ryanoasis/vim-devicons'

  " Floaterm: floating terminal windows (works in vim + nvim).
  " Used for the lazygit popup below.
  Plug 'voldikss/vim-floaterm'

  " kdheepak/lazygit.nvim is nvim-only; replaced by vim-floaterm + lazygit.
  " Plug 'kdheepak/lazygit.nvim'


  " *******  Key mappings *************
  " [command: w!!] Allow to gain root permission within vim
  cmap w!! w !sudo tee >/dev/null %

  " *******  Load vim-plug Plugins  *************
  " All of your Plugins must be added before the following line
  call plug#end()            " required
  filetype plugin indent on    " required
endif



" *******  Plugin Configuration *************

" Basic theme config 
set background=dark

" Catppuccin theme (mocha flavour):
"   https://github.com/catppuccin/vim
silent! colorscheme catppuccin_mocha

" Subtle 80-col ruler instead of catppuccin's loud red (apply now + on future :colorscheme)
highlight ColorColumn ctermbg=237 guibg=#313244
autocmd ColorScheme * highlight ColorColumn ctermbg=237 guibg=#313244

" Spell off on code/config filetypes (keep it for markdown, txt, gitcommit, etc.)
autocmd FileType yaml,yml,json,toml,sh,zsh,bash,vim,lua,javascript,typescript,python,go,rust,sql,dockerfile,gitconfig,conf,tmux,make,cmake,xml,html,css,scss,dosini,crontab,nginx setlocal nospell


" Use ag instead of grep, in the :grep command
if executable('ag') && HasPlugins('ack.vim')
  " bind \ (backward slash) to grep shortcut
  command! -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
  nnoremap \ :Ack<SPACE>


  " Use ag (the_silver_searcher) instead of ack
  "     https://github.com/mileszs/ack.vim#can-i-use-ag-the-silver-searcher-with-this 
  let g:ackprg = 'ag --vimgrep'

  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = [
        \ '.git', 'cd %s && git ls-files . -co --exclude-standard',
        \ 'ag %s -l --nocolor -g ""'
        \ ]

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" NerdTree conf
if HasPlugins('nerdtree')
  " Auto-close the tree when you pick a file (modal-ish feel)
  let g:NERDTreeQuitOnOpen=1

  " Smart toggle: opens with cursor on current file; press <C-n> again to close
  function! NerdTreeSmartToggle()
    if g:NERDTree.IsOpen()
      NERDTreeClose
    elseif filereadable(expand('%'))
      NERDTreeFind
    else
      NERDTreeToggle
    endif
  endfunction
  nnoremap <silent> <C-n> :call NerdTreeSmartToggle()<CR>
  map <C-m> :NERDTreeFind<CR>

  " Open nerd tree as an only window, with the current file
  " selected
  fun! NewTreeOpen()
    NERDTreeFind
    wincmd o
  endfun
  nmap <silent><leader>no :call NewTreeOpen()<CR>
endif

" LazyGit via vim-floaterm (floating terminal, works in vim + nvim).
" <leader>gg opens fugitive status; <leader>lg opens lazygit in a float.
if HasPlugins('vim-floaterm') && executable('lazygit')
  let g:floaterm_width  = 0.9
  let g:floaterm_height = 0.9
  nnoremap <silent> <leader>lg :FloatermNew --autoclose=2 lazygit<CR>
  nnoremap <silent> <leader>ll :FloatermNew --autoclose=2 lazygit<CR>
endif
" nnoremap <silent> <leader>lg :LazyGit<CR>  " replaced by floaterm above

" Fugitive: git bindings
nnoremap <silent> <leader>gg :Git<CR>
nnoremap <silent> <leader>gd :Gdiffsplit<CR>
nnoremap <silent> <leader>gb :Git blame<CR>
nnoremap <silent> <leader>gl :Git log<CR>
nnoremap <silent> <leader>gc :Git commit<CR>
nnoremap <silent> <leader>gS :Gwrite<CR>
nnoremap <silent> <leader>gR :Gread<CR>
" Rhubarb: GitHub link of current file/line
nnoremap <silent> <leader>gy :.GBrowse!<CR>
xnoremap <silent> <leader>gy :GBrowse!<CR>
nnoremap <silent> <leader>gY :.GBrowse<CR>
xnoremap <silent> <leader>gY :GBrowse<CR>

" CoC: Conquer Of Completion
if HasPlugins('coc.nvim')
  "--------------------------------------------------------------------------
  " CoC custom comfig
  " --------------------------------------------------------------------------
  let g:coc_global_extensions = [
        \ 'coc-tsserver',
        \ 'coc-json',
        \ 'coc-html',
        \ 'coc-css',
        \ 'coc-pyright',
        \ 'coc-solidity',
        \ 'coc-docker',
        \ 'coc-eslint',
        \ 'coc-git',
        \ 'coc-lua',
        \ 'coc-markdownlint',
        \ 'coc-markdown-preview-enhanced',
        \ 'coc-nav',
        \ 'coc-prettier',
        \ 'coc-rust-analyzer',
        \ 'coc-sh',
        \ 'coc-sql',
        \ 'coc-symbol-line',
        \ 'coc-toml',
        \ 'coc-xml',
        \ 'coc-yaml'
        \ ]
  
  "--------------------------------------------------------------------------
  " CoC recommened comfig 
  " --------------------------------------------------------------------------
	" May need for Vim (not Neovim) since coc.nvim calculates byte offset by count
	" utf-8 byte sequence
	set encoding=utf-8
	" Some servers have issues with backup files, see #649
	set nobackup
	set nowritebackup

	" Having longer updatetime (default is 4000 ms = 4s) leads to noticeable
	" delays and poor user experience
	set updatetime=300

	" Always show the signcolumn, otherwise it would shift the text each time
	" diagnostics appear/become resolved
	set signcolumn=yes

	" Use tab for trigger completion with characters ahead and navigate
	" NOTE: There's always complete item selected by default, you may want to enable
	" no select by `"suggest.noselect": true` in your configuration file
	" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
	" other plugin before putting this into your config
	inoremap <silent><expr> <TAB>
				\ coc#pum#visible() ? coc#pum#next(1) :
				\ CheckBackspace() ? "\<Tab>" :
				\ coc#refresh()
	inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

	" Make <CR> to accept selected completion item or notify coc.nvim to format
	" <C-g>u breaks current undo, please make your own choice
	inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
																\: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

	function! CheckBackspace() abort
		let col = col('.') - 1
		return !col || getline('.')[col - 1]  =~# '\s'
	endfunction

	" Use <c-space> to trigger completion
	if has('nvim')
		inoremap <silent><expr> <c-space> coc#refresh()
	else
		inoremap <silent><expr> <c-@> coc#refresh()
	endif

	" Use `[g` and `]g` to navigate diagnostics
	" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list
	nmap <silent> [g <Plug>(coc-diagnostic-prev)
	nmap <silent> ]g <Plug>(coc-diagnostic-next)

	" GoTo code navigation
	nmap <silent> gd <Plug>(coc-definition)
	nmap <silent> gy <Plug>(coc-type-definition)
	nmap <silent> gi <Plug>(coc-implementation)
	nmap <silent> gr <Plug>(coc-references)

	" Use K to show documentation in preview window
	nnoremap <silent> K :call ShowDocumentation()<CR>

	function! ShowDocumentation()
		if CocAction('hasProvider', 'hover')
			call CocActionAsync('doHover')
		else
			call feedkeys('K', 'in')
		endif
	endfunction

	" Highlight the symbol and its references when holding the cursor
	autocmd CursorHold * silent call CocActionAsync('highlight')

	" Symbol renaming
	nmap <leader>rn <Plug>(coc-rename)

	" Formatting selected code
	xmap <leader>f  <Plug>(coc-format-selected)
	nmap <leader>f  <Plug>(coc-format-selected)

	augroup mygroup
		autocmd!
		" Setup formatexpr specified filetype(s)
		autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
		" Update signature help on jump placeholder
		autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
	augroup end

	" Applying code actions to the selected code block
	" Example: `<leader>aap` for current paragraph
	xmap <leader>a  <Plug>(coc-codeaction-selected)
	nmap <leader>a  <Plug>(coc-codeaction-selected)

	" Remap keys for applying code actions at the cursor position
	nmap <leader>ac  <Plug>(coc-codeaction-cursor)
	" Remap keys for apply code actions affect whole buffer
	nmap <leader>as  <Plug>(coc-codeaction-source)
	" Apply the most preferred quickfix action to fix diagnostic on the current line
	nmap <leader>qf  <Plug>(coc-fix-current)

	" Remap keys for applying refactor code actions
	nmap <silent> <leader>re <Plug>(coc-codeaction-refactor)
	xmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)
	nmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)

	" Run the Code Lens action on the current line
	nmap <leader>cl  <Plug>(coc-codelens-action)

	" Map function and class text objects
	" NOTE: Requires 'textDocument.documentSymbol' support from the language server
	xmap if <Plug>(coc-funcobj-i)
	omap if <Plug>(coc-funcobj-i)
	xmap af <Plug>(coc-funcobj-a)
	omap af <Plug>(coc-funcobj-a)
	xmap ic <Plug>(coc-classobj-i)
	omap ic <Plug>(coc-classobj-i)
	xmap ac <Plug>(coc-classobj-a)
	omap ac <Plug>(coc-classobj-a)

	" Remap <C-f> and <C-b> to scroll float windows/popups
	if has('nvim-0.4.0') || has('patch-8.2.0750')
		nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
		nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
		inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
		inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
		vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
		vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
	endif

	" Use CTRL-S for selections ranges
	" Requires 'textDocument/selectionRange' support of language server
	nmap <silent> <C-s> <Plug>(coc-range-select)
	xmap <silent> <C-s> <Plug>(coc-range-select)

	" Add `:Format` command to format current buffer
	command! -nargs=0 Format :call CocActionAsync('format')

	" Add `:Fold` command to fold current buffer
	command! -nargs=? Fold :call     CocAction('fold', <f-args>)

	" Add `:OR` command for organize imports of the current buffer
	command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')

	" Add (Neo)Vim's native statusline support
	" NOTE: Please see `:h coc-status` for integrations with external plugins that
	" provide custom statusline: lightline.vim, vim-airline
	set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

	" Mappings for CoCList
	" Show all diagnostics
	nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
	" Manage extensions
	nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
	" Show commands
	nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
	" Find symbol of current document
	nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
	" Search workspace symbols
	nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
	" Do default action for next item
	nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
	" Do default action for previous item
	nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
	" Resume latest coc list
	nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
endif

" Tern: tern mappings
if exists(':TernRefs')
  nnoremap <silent> <F2> :TernRefs<CR>
  nnoremap <silent> <F3> :TernDef<CR>
endif

" Ale lintern (https://github.com/w0rp/ale)
if HasPlugins('ale')
  "let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
endif

" Tagbar: Display tags in a window
"   https://github.com/majutsushi/tagbar
if exists(':TagbarToggle')
  nmap <F8> :TagbarToggle<CR>
endif


" Status bar - Vim airline conf
if HasPlugins('vim-airline')
  set laststatus=2 "  Solution for vim-airline doesn't appear until I create a new split problem
  let g:airline_theme='catppuccin_mocha'
endif

" ctrlp_bdelete: Close open bufferes extension by j5shi/ctrlp_bdelete
"   https://github.com/d11wtq/ctrlp_bdelete.vim
if HasPlugins('ctrlp_bdelete.vim')
  "   Select the buffer and close it with ctrl-2 (also works with ctrl-z multi
  "   selection)
  if exists('*ctrlp_bdelete#init')
    call ctrlp_bdelete#init()
  endif
endif

" Ctrlp: Open files by name
if HasPlugins('ctrlp.vim')
  let g:ctrlp_map =  '<c-p>' "     Map ctr+p key to ctrlp (will be overrided by fzf below)
  let g:ctrlp_map =  '<leader>p' " Map <leader>+p key to ctrlp
  let g:ctrlp_cmd = 'CtrlP'

  " Ctrlp: Open with ctrl-b the buffers (will be overrided by fzf below)
  map <c-b> :CtrlPBuffer<CR>

  " Ctrlp: Open with ctrl-p (will be overrided by fzf below)
  map <c-p> :CtrlP<CR>

  " Ctrlp: Ignore .gitignore files
  let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
  let g:ctrlp_user_command = [
      \ '.git', 'cd %s && git ls-files . -co --exclude-standard',
      \ 'find %s -type f'
      \ ]
endif


" FZF config
"   fzf provides fuzzy search menus for buffers and files
"   Uses fzf bin, the fzf.vim plugin, and some hack function to add images
if executable('fzf')
  " fzf config
  map <leader>P :GFiles<CR>
  map <C-p> :Files<CR>
  map <C-b> :Buffers<CR>
  " Double-leader (Space Space) for fuzzy file open
  nnoremap <silent> <leader><leader> :Files<CR>

  " Search/grep bindings (mirroring nvim Snacks.picker)
  nnoremap <silent> <leader>/ :Rg<CR>
  nnoremap <silent> <leader>, :Buffers<CR>
  nnoremap <silent> <leader>: :History:<CR>
  " <leader>e — file explorer (NerdTree, finds current file)
  nnoremap <silent> <leader>e :NERDTreeFind<CR>
  " <leader>f* — find
  nnoremap <silent> <leader>ff :Files<CR>
  nnoremap <silent> <leader>fg :GFiles<CR>
  nnoremap <silent> <leader>fb :Buffers<CR>
  nnoremap <silent> <leader>fr :History<CR>
  nnoremap <silent> <leader>fh :Helptags<CR>
  " <leader>s* — search
  nnoremap <silent> <leader>sg :Rg<CR>
  nnoremap          <leader>sw :Rg <C-r><C-w><CR>
  xnoremap          <leader>sw y:Rg <C-r>"<CR>
  nnoremap <silent> <leader>sb :BLines<CR>
  nnoremap <silent> <leader>sm :Marks<CR>
  nnoremap <silent> <leader>sk :Maps<CR>
  nnoremap <silent> <leader>sC :Commands<CR>
  nnoremap <silent> <leader>s/ :History/<CR>
  nnoremap <silent> <leader>sh :Helptags<CR>

  if executable('devicon-lookup') 
    map <C-p> :call FZFWithDevIcons()<CR>

    " Small hack for adding icons to fzf
    "   - fzf for now doesn't have a  dev-icons integration
    "   - The code below substitutes the :Files command
    function! FZFWithDevIcons()
      let l:fzf_files_options = ' -m --bind ctrl-d:preview-page-down,ctrl-u:preview-page-up --preview "bat --color always --style numbers {2..}"'

      function! s:files()
        let l:files = split(system($FZF_DEFAULT_COMMAND.'| devicon-lookup'), '\n')
        return l:files
      endfunction

      function! s:edit_file(items)
        let items = a:items
        let i = 1
        let ln = len(items)
        while i < ln
          let item = items[i]
          let parts = split(item, ' ')
          let file_path = get(parts, 1, '')
          let items[i] = file_path
          let i += 1
        endwhile
        call s:Sink(items)
      endfunction

      let opts = fzf#wrap({})
      let opts.source = <sid>files()
      let s:Sink = opts['sink*']
      let opts['sink*'] = function('s:edit_file')
      let opts.options .= l:fzf_files_options
      call fzf#run(opts)
    endfunction
  endif
endif

" Easy motion (https://github.com/easymotion/vim-easymotion)
if HasPlugins('vim-easymotion')
  " (g:EasyMotion_do_mapping=0 set near the Plug line above so it takes effect before plugin loads)
  " Jump to anywhere you want with minimal keystrokes, with just one key binding.
  " `s{char}{label}`
  "nmap s <Plug>(easymotion-overwin-f)
  " or
  " `s{char}{char}{label}`
  " Need one more keystroke, but on average, it may be more comfortable.
  nmap <leader>2 <Plug>(easymotion-overwin-f2)

  " Open easymotion search box (moved from <leader>/ — that's now :Rg grep)
  map  <leader>? <Plug>(easymotion-sn)
  omap <leader>? <Plug>(easymotion-tn)

  " Turn on case insensitive feature
  let g:EasyMotion_smartcase = 1

  " JK motions: Line motions
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)
endif

" Disable the formatting to test 'Chiel92/vim-autoformat'

" vim-jsbeautify: HTML, CSS, JS formatter
if exists(':Autoformat')
  " Format: Formats using configurable external formatters: Chiel92/vim-autoformat
  "     c-f                       Auto format
  "     gg=G                      manually autoindent
  "     :retab                    retab
  "     :RemoveTrailingSpaces     remove trailing whitespace
  noremap <c-f> gg=G``
  let g:formatter_yapf_style = 'pep8'
endif

" TODOS:
"     - Find and replace: https://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
"
