#!/bin/bash
set -e

# Neovim setup — single config, standard NVIM_APPNAME layout kept for continuity
# (previously supported multiple configs; see git log for the multi-config
# machinery if you ever need it back).
#
# Dependencies:
#   Required:  git, neovim
#   Optional (auto-installed if toolchain present):
#     - npm: neovim (Node provider), vscode-langservers-extracted, vscode-solidity-server,
#            prettier, @mermaid-js/mermaid-cli
#     - pip: pynvim (Python provider)
#     - cargo: stylua (Lua formatter)
#
#   Without Node/Python/Cargo nvim still works; :checkhealth will nag.

DOT_FILES="$HOME/dotfiles"
NVIM_DOTFILES="$DOT_FILES/nvim"
NVIM_TARGET="$HOME/.config/nvim-custom"   # NVIM_APPNAME=nvim-custom launches this

declare -a NPM_PACKAGES=(
  "neovim"                        # Node provider (removes :checkhealth warning)
  "vscode-langservers-extracted"  # HTML/CSS/JSON/ESLint language servers
  "vscode-solidity-server"        # Solidity language server
  "prettier"                      # Code formatter (conform.nvim)
  "@mermaid-js/mermaid-cli"       # Mermaid diagram renderer (snacks.nvim)
)

declare -a PYTHON_PACKAGES=(
  "pynvim"  # Python provider (ruff is installed as a system tool in install-apps_*.sh)
)

declare -a CARGO_PACKAGES=(
  "stylua"  # Lua formatter (conform.nvim)
)

header() {
  printf "\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
  printf "Neovim Setup\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
}

setup_symlink() {
  local TIME_STAMP=$(date +%F_%R)
  local BACKUP_DIR="$DOT_FILES/backup/nvim_$TIME_STAMP"

  if [ -d "$NVIM_TARGET" ] || [ -L "$NVIM_TARGET" ]; then
    printf "[dotfiles-nvim] Backing up existing %s -> %s\n" "$NVIM_TARGET" "$BACKUP_DIR"
    mkdir -p "$BACKUP_DIR"
    cp -rf "$NVIM_TARGET" "$BACKUP_DIR/" 2>/dev/null || :
    rm -rf "$NVIM_TARGET"
  fi

  # Clean plugin / state caches so lazy.nvim reinstalls cleanly
  rm -rf "$HOME/.local/share/nvim-custom" "$HOME/.local/state/nvim-custom" 2>/dev/null || :

  printf "[dotfiles-nvim] Linking %s -> %s\n" "$NVIM_TARGET" "$NVIM_DOTFILES"
  mkdir -p "$(dirname "$NVIM_TARGET")"
  ln -sf "$NVIM_DOTFILES" "$NVIM_TARGET"
}

install_npm() {
  command -v npm >/dev/null 2>&1 || {
    printf "\n  ⚠️  npm not installed — skipping: %s\n" "${NPM_PACKAGES[*]}"
    return
  }
  printf "\n  📦 Installing Node.js packages:\n"
  for pkg in "${NPM_PACKAGES[@]}"; do
    printf "    - %s: " "$pkg"
    npm install -g "$pkg" >/dev/null 2>&1 && echo "✓" || echo "⚠️  failed"
  done
}

install_pip() {
  local PIP
  if command -v pip3 >/dev/null 2>&1; then PIP=pip3
  elif command -v pip  >/dev/null 2>&1; then PIP=pip
  else
    printf "\n  ⚠️  pip not installed — skipping: %s\n" "${PYTHON_PACKAGES[*]}"
    return
  fi
  printf "\n  🐍 Installing Python packages (via %s):\n" "$PIP"
  for pkg in "${PYTHON_PACKAGES[@]}"; do
    printf "    - %s: " "$pkg"
    "$PIP" install --quiet "$pkg" && echo "✓" || echo "⚠️  failed"
  done
}

install_cargo() {
  command -v cargo >/dev/null 2>&1 || {
    printf "\n  ⚠️  cargo not installed — skipping: %s\n" "${CARGO_PACKAGES[*]}"
    return
  }
  printf "\n  🦀 Installing Cargo packages:\n"
  for pkg in "${CARGO_PACKAGES[@]}"; do
    printf "    - %s: " "$pkg"
    cargo install "$pkg" --quiet >/dev/null 2>&1 && echo "✓" || echo "✓ (already installed or updated)"
  done
}

create_zsh_alias() {
  local ZSH_NVIM_FILE="$HOME/.zsh/nvim.zsh"
  mkdir -p "$HOME/.zsh"
  cat > "$ZSH_NVIM_FILE" <<'EOF'
# Generated by ~/dotfiles/install/dotfiles_nvim.sh
# Launches ~/.config/nvim-custom via NVIM_APPNAME=nvim-custom.
export NVIM_APPNAME=nvim-custom
EOF
  printf "[dotfiles-nvim] Wrote zsh init at %s\n" "$ZSH_NVIM_FILE"
}

print_next_steps() {
  printf "\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
  printf "✓ Neovim configured\n\n"
  printf "First launch:\n"
  printf "  - lazy.nvim auto-installs plugins\n"
  printf "  - Mason installs LSP servers\n"
  printf "  - Takes 2–3 minutes\n\n"
  printf "Troubleshoot:  nvim +checkhealth\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
}

header
setup_symlink
install_npm
install_pip
install_cargo
create_zsh_alias
print_next_steps
