# Setup fzf
# ---------
# fzf lives inside the dotfiles repo (bin-dependencies/fzf). Use $HOME so this
# works for any user. (Originally generated by `fzf install` with hardcoded paths.)
FZF_BIN="$HOME/dotfiles/bin-dependencies/fzf/bin"
if [[ ! "$PATH" == *"$FZF_BIN"* ]]; then
  export PATH="${PATH:+${PATH}:}$FZF_BIN"
fi

# Auto-completion
# ---------------
# [[ $- == *i* ]] && source "$HOME/dotfiles/bin-dependencies/fzf/shell/completion.zsh" 2> /dev/null

# Key bindings
# ------------
# source "$HOME/dotfiles/bin-dependencies/fzf/shell/key-bindings.zsh"
