##########################
#  ZSH DIRS              #
##########################

# dotfiles zsh dir (holds user-written modules like common.zsh, plugins.zsh, theme_p10k.zsh)
export ZSH_BASE=~/dotfiles/zsh

# Oh My Zsh lives at its canonical location now (was vendored in dotfiles as a submodule).
# Bootstrap a fresh machine with: bash ~/dotfiles/install/install-zsh.sh
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"

#############################
#  THEME                    #
#############################

source $ZSH_BASE/theme_p10k.zsh

##########################
#  GENERAL ZSH CONFIG    #
##########################

# Default prompt
PROMPT='%F{red}%n%f@%F{blue}%m%f %F{yellow}%1~%f %# '
RPROMPT='[%F{yellow}%?%f]'

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=30

# Default editor
export EDITOR='nvim'

# Check for new versions every month
export UPDATE_ZSH_DAYS=30


##########################
#  PLUGINS               #
##########################
source $ZSH_BASE/plugins.zsh

##############################################################
#  Configure OH MY ZSH and SOME DEFAULTS if not available    #
##############################################################
# Configure Oh My ZSH if present
if [ -f "$ZSH/oh-my-zsh.sh" ]; then
  source $ZSH/oh-my-zsh.sh
else
  # Default config for when Oh My ZSH is not avaliable
  source $ZSH_BASE/oh-my-zsh-unavailable.zsh
fi

###############################
#  LOAD COMMON CONFIG         #
###############################

source $ZSH_BASE/common.zsh


###############################
#  Add some local paths       #
###############################

export PATH="$HOME/.local/bin:$PATH"

###############################
#  LOAD SOME LOCAL CONFIG    #
###############################

# Load local config: Machine specific config:
#    See:
#      ~/.zsh-local
if [[ -a ~/.zsh ]]; then	
  # Read all config files in ~/.zsh
  for file in ~/.zsh/*.zsh; do
    #echo "Loading: $file"
    source "$file"
  done
fi

