# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

##########################
#  ZSH DIRS              #
##########################

# dotfiles zsh dir (holds user-written modules like common.zsh, plugins.zsh, theme_p10k.zsh)
export ZSH_BASE=~/dotfiles/zsh

# Oh My Zsh lives at its canonical location now (was vendored in dotfiles as a submodule).
# Bootstrap a fresh machine with: bash ~/dotfiles/install/install-zsh.sh
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"

#############################
#  THEME                    #
#############################

source $ZSH_BASE/theme_p10k.zsh

##########################
#  GENERAL ZSH CONFIG    #
##########################

# Default prompt
PROMPT='%F{red}%n%f@%F{blue}%m%f %F{yellow}%1~%f %# '
RPROMPT='[%F{yellow}%?%f]'

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=30

# Default editor
export EDITOR='nvim'

# Check for new versions every month
export UPDATE_ZSH_DAYS=30


##########################
#  PLUGINS               #
##########################
source $ZSH_BASE/plugins.zsh

##############################################################
#  Configure OH MY ZSH and SOME DEFAULTS if not available    #
##############################################################
# Configure Oh My ZSH if present
if [ -f "$ZSH/oh-my-zsh.sh" ]; then
  source $ZSH/oh-my-zsh.sh
else
  # Default config for when Oh My ZSH is not avaliable
  source $ZSH_BASE/oh-my-zsh-unavailable.zsh
fi

###############################
#  LOAD COMMON CONFIG         #
###############################

source $ZSH_BASE/common.zsh

###############################
#  THEME (light/dark)         #
###############################

source $ZSH_BASE/theme.zsh


###############################
#  Add some local paths       #
###############################

export PATH="$HOME/.local/bin:$PATH"

###############################
#  LOAD SOME LOCAL CONFIG    #
###############################

# Load local config: Machine specific config:
#    See:
#      ~/.zsh-local
if [[ -a ~/.zsh ]]; then	
  # Read all config files in ~/.zsh
  for file in ~/.zsh/*.zsh; do
    #echo "Loading: $file"
    source "$file"
  done
fi

export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# To customize prompt, run `p10k configure` or edit ~/dotfiles/zsh/p10k-light.zsh.
[[ ! -f ~/dotfiles/zsh/p10k-light.zsh ]] || source ~/dotfiles/zsh/p10k-light.zsh
